spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=COMIC_SHOP_HSF302;encrypt=false;
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# ho tro paging
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect
# Disable template cache for development
spring.thymeleaf.cache=false
# Enable hot reload
spring.devtools.restart.enabled=true
# Exclude static resources from restart
spring.devtools.restart.exclude=static/**,public/**
# LiveReload
spring.devtools.livereload.enabled=true
# Allow bean definition overriding
#spring.main.allow-bean-definition-overriding=true
# File upload configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=uploads
#CONFIGRUTION EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sihira7075@gmail.com
spring.mail.password=nefriithkojwnlum
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
# ========== VNPay Configuration ==========
vnpay.tmn-code=N0HTKEBM
vnpay.hash-secret=KQDVN8EO4ZIZ55CNE7PB6ABR7OAN2M28
vnpay.payment-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8080/vnpay-return
vnpay.api-url=https://sandbox.vnpayment.vn/merchant_weblog/Download
# ========== VNPay Sandbox Configuration (for testing) ==========
# Khi deploy production, thay ??i thành:
# vnpay.payment-url=https://pay.vnpayment.vn/paymentv2/vpcpay.html
